# config/zed_yolo.yaml
# Parameters for YOLO Custom Object Detection component

---
/**:
    ros__parameters:

      general:
        conf_thresh: 0.3 # [DYNAMIC] Detection confidence threshold
        nms_thresh: 0.4 # [DYNAMIC] Non-Maximum Suppression threshold
        publish_debug_img: true # Publish a debug image showing the detected object bounding boxes

      yolo_engine:
        build_engine: false
        onnx_model: '~/Downloads/yolov8n.onnx'  # YOLO ONNX model full file path
        engine_path: '~/zed_custom_od'  # Generated YOLO engine path
        engine_name: 'zed_yolo.engine'  # Generated YOLO engine NAME
        img_size: 608 # Image size, squared: "size x size"

